packages:
  - "packages/*"
  - "apps/*"

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

catalog:
  typescript: ^5.7.3
  eslint: ^9.18.0
  prettier: ^3.4.2
  eslint-config-prettier: ^10.0.1
  eslint-plugin-prettier: ^5.2.2
  typescript-eslint: ^8.20.0
  zod: ^4.2.1
  '@types/node': ^22.10.7
