const QUERY_KEYS = {
  TWITCH_USERS: "TWITCH_USERS",
  USER_TWITCH_CHANNEL_ASSIGNMENTS: "USER_TWITCH_CHANNEL_ASSIGNMENTS",
  GET_ADDED_CHANNELS: "GET_ADDED_CHANNELS",
};

Object.freeze(QUERY_KEYS);

export default QUERY_KEYS;
